Adds GitHub default tracking section
CreativeSolutionsGroup/wiki pull request #30
Opened 2023-08-30 16:36 UTC by SebastianNeiswanger

Lays out how to set up default tracking in a new section. Tested by yours truly to know it works.

2023-08-30 21:15 UTC, ashlyndevries requested changes

2023-08-30 21:15 UTC, ashlyndevries commented on Dev-Tools/github/tool.md
> +   1. If you are not updated make sure to update git before continuing and refresh your terminal
Include steps on how to update git.

2023-08-31 16:36 UTC, SebastianNeiswanger commented on Dev-Tools/github/tool.md
> +   1. If you are not updated make sure to update git before continuing and refresh your terminal
I have added a section for that now

2023-08-31 18:46 UTC, ashlyndevries requested changes
@SpBills, LGTY?

2023-08-31 20:33 UTC, ashlyndevries approved these changes
LGTM

2023-08-31 20:33 UTC, merged